### ISSUE TITLE
 Data processing issues on S3DIS

### ISSUE THREAD

**Issue by zivlzw** [LiyaoTang/ERDA#1]
We confirm that the environment and related libraries have been configured as required, but when preparing the S3DIS dataset, the pkl file could not be generated after the ply file was successfully generated and an error was reported as follows. Is it convenient for you to upload a copy of the processed S3DIS dataset?

```
Availabel Mem of each GPU: 124268
Traceback (most recent call last):File "main.  py", line 100, in <module>trainer.  train()
File "/root/ERDA-main/utils/trainer.py", line 66, in traing= GraphBuilder (config, verbose-self.verbose)
File "/root/ERDA-main/utils/tf_graph_builder.py", line 47, in__init-dataset= self.  get_dataset (config, verbose)
File "/root/ERDA-main/models/../datasets/tf_s3dis_dataset.py", line 112, in__init,lself.  load_subsampled_clouds(config.  first_subsampling_dl, verbose-verbose
File "/root/ERDA-main/models/.. /datasets/tf_s3dis dataset.py", line 650, in load subsanpled_clouds_alignedsub_xyz, sub_colors, sub_labels= grid_subsampling (xyz, colors, labels, subsampling_parameter)
File "/root/ERDA-main/ops/tf_ops.py", line 121, in grid_subsamplingreturn cpp_subsampling,compute(points, features-features, classes-labels, sanpleDl-sampleDl, verbose-verbose)
AttributeError: module ops.  cpp wrappers.  cpp subsampling, grid subsampling' has no attribute'compute
```

**Comment by zivlzw** [comment]
> We confirm that the environment and related libraries have been configured as required, but when preparing the S3DIS dataset, the pkl file could not be generated after the ply file was successfully generated and an error was reported as follows. Is it convenient for you to upload a copy of the processed S3DIS dataset?
> 
> ```
> Availabel Mem of each GPU: 124268
> Traceback (most recent call last):File "main.  py", line 100, in <module>trainer.  train()
> File "/root/ERDA-main/utils/trainer.py", line 66, in traing= GraphBuilder (config, verbose-self.verbose)
> File "/root/ERDA-main/utils/tf_graph_builder.py", line 47, in__init-dataset= self.  get_dataset (config, verbose)
> File "/root/ERDA-main/models/../datasets/tf_s3dis_dataset.py", line 112, in__init,lself.  load_subsampled_clouds(config.  first_subsampling_dl, verbose-verbose
> File "/root/ERDA-main/models/.. /datasets/tf_s3dis dataset.py", line 650, in load subsanpled_clouds_alignedsub_xyz, sub_colors, sub_labels= grid_subsampling (xyz, colors, labels, subsampling_parameter)
> File "/root/ERDA-main/ops/tf_ops.py", line 121, in grid_subsamplingreturn cpp_subsampling,compute(points, features-features, classes-labels, sanpleDl-sampleDl, verbose-verbose)
> AttributeError: module ops.  cpp wrappers.  cpp subsampling, grid subsampling' has no attribute'compute
> ```
We have solved this problem and it is the reason that the library does not compile well.

**Comment by LiyaoTang** [comment]
Hi,

Thanks for your interest. Glad that you have solved the problem.

Cheers,
Liyao

**Comment by mooncakehub** [comment]
![1700040342587](https://github.com/LiyaoTang/ERDA/assets/138660085/aaf5a15d-1438-4ca2-8feb-256853fc112a)
when I process the S3DIS,I met this error,did you meet

**Comment by LiyaoTang** [comment]
Hi,

Thanks for your interest.

It seems that you use the wrong files. We use the 'Aligned_Version'. Could you check that?

Best,
Liyao

**Comment by mooncakehub** [comment]
my dataset is 'Aligned_Version', and Area1-Area4 has been processed successfully. I don't know why there is '_1.2' in the path

**Comment by mooncakehub** [comment]
than you for your reply. I check my dataset,it's definit ' Aligned_Version',but the method of processed dataset is for ' Stanford3dDataset_v1.2'. so I check the code. I found that default version is 'aligned',but when processed,it became 'full'.I don't know how did this happen,so I modified the version 'aligned'
![微信图片_20231116100158](https://github.com/LiyaoTang/ERDA/assets/138660085/d4232363-7e97-4ffa-aa67-30cb164c3572)
![微信图片_20231116100229](https://github.com/LiyaoTang/ERDA/assets/138660085/3e12d7ce-50ca-4299-ae47-0d18271697b3)

**Comment by mooncakehub** [comment]
How much video memory is needed to process the s3dis dataset, I use 4 2080TI gpus, the computer will automatically shut down and abort the process

**Comment by LiyaoTang** [comment]
Hi,

It's probably the problem with the config that you use, please check the version in the config and if it changes during the code execution.

It's also glad to see that you made some progress. To process the S3DIS for the first time, I would recommend having around 64GB CPU mem.

**Comment by mooncakehub** [comment]
Hi，
I  am really grateful for your reply.
I  used 'free- h' to check CPU mem, the CPU mem is enough.so Do you mean that the GPU has 64G of video mem

**Comment by mooncakehub** [comment]
![Uploading 1700183747906.png…]()

**Comment by mooncakehub** [comment]
![1700183747906](https://github.com/LiyaoTang/ERDA/assets/138660085/29320979-04bb-47b1-a05e-c78096867c3f)

**Comment by LiyaoTang** [comment]
Hi,

It seems your hardware should be fine to run the code.
Could you check the log and try to provide more details (output printing / trace-back if any ) regarding the process shut-down?
